# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E8DAD0
background         #2B2624
cursor             #B19B8B

active_tab_foreground     #2B2624
active_tab_background     #E8DAD0
inactive_tab_foreground   #E8DAD0
inactive_tab_background   #2B2624

active_border_color   #E8DAD0
inactive_border_color #2B2624
bell_border_color     #4B3729

color0      #514C49
color1		#4B3729
color2		#5C4535
color3		#6D5441
color4		#7D624D
color5		#8E715A
color6		#8E715A
color7		#D6C2B3
color8		#96887D
color9		#654936
color10		#7B5C47
color11		#916F57
color12		#A78367
color13		#BE9677
color14		#BE9677
color15		#D6C2B3
