# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2B2624)
$foreground = rgb(E8DAD0)
$color0 = rgb(514C49)
$color1 = rgb(4B3729)
$color2 = rgb(5C4535)
$color3 = rgb(6D5441)
$color4 = rgb(7D624D)
$color5 = rgb(8E715A)
$color6 = rgb(8E715A)
$color7 = rgb(D6C2B3)
$color8 = rgb(96887D)
$color9 = rgb(654936)
$color10 = rgb(7B5C47)
$color11 = rgb(916F57)
$color12 = rgb(A78367)
$color13 = rgb(BE9677)
$color14 = rgb(BE9677)
$color15 = rgb(D6C2B3)
